spring:
  application:
    name: eureka-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.50.106:3306/shinan
    username: root
    password: root
  profiles:
    active: dev1
dev:
  host: localhost
  dev1Port: 8761
  dev2Port: 8762
  dev3Port: 8763
eureka:
  server:
    enable-self-preservation: false