spring:
  application:
    name: cloud-consumer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.50.112:3306/shinan
    username: root
    password: root
server:
  port: 8080