spring:
  application:
    name: cloud-consumerfeign-hystrix
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.191:3306/shinan
    username: root
    password: root
server:
  port: 8080
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true